# Generated by Django 2.2.16 on 2022-07-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20220715_1259'),
        ('users', '0005_alter_user_id'),
    ]

    operations = [
    ]
