# Generated by Django 2.2.16 on 2022-07-15 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20220715_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=uuid.UUID('6274d232-044b-11ed-93a1-18c04d9f4202'), max_length=50, verbose_name='Код для авторизации'),
        ),
    ]
