# Generated by Django 2.2.16 on 2022-07-15 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220715_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=uuid.UUID('4820a9ab-044a-11ed-9cfb-18c04d9f4202'), max_length=50, verbose_name='Код для авторизации'),
        ),
    ]
