# Generated by Django 2.2.16 on 2022-07-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220715_1935'),
        ('users', '0010_auto_20220715_1927'),
    ]

    operations = [
    ]
