# Generated by Django 2.2.16 on 2022-07-15 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20220715_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=uuid.UUID('03de9a69-0453-11ed-9296-18c04d9f4202'), max_length=50, verbose_name='Код для авторизации'),
        ),
    ]
